name: Docker Image CI
on:
  push:
    tags:
      - 'v*'
  schedule:
    - cron: 0 4 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set variables
        id: vars
        run: |
          echo "repository=${GITHUB_ACTOR}/sls-dashboard" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          pull: true
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.version }}
